#pragma once

const int firstHeight = 119;	// 34(screen height) * 3 = 102 + 17 (half-screen height) = 119
const int firstWidth = 61;

string FirstStage[] =
{
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
	"BFFFFFFWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWFFFFFFB",
	"BFFFFFWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWFFFFFB",
	"BFFFF                                                   FFFFB",
	"BFFF                                                     FFFB",
	"BFF                                                       FFB",
	"BF                                                         FB",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B        WWWWWWWWW                        WWWWWWWWWW        B",
	"B        WWWWWWWWW                        WWWWWWWWWW        B",
	"B        WWWWWWWWW                        WWWWWWWWWW        B",
	"B        WWWWWWWWW                        WWWWWWWWWW        B",
	"B          bbbb                              bbbb           B",
	"B        bbbbbbbb                          bbbbbbbb         B",
	"BbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbB",
	"B      bbbbbbbbbbbb       WWWWWWWWW      bbbbbbbbbbbb       B",
	"B        bbbbbbbb         WWWWWWWWW        bbbbbbbb         B",
	"B          bbbb                              bbbb           B",
	"B                                                           B",
	"B                                                           B",
	"B       BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB       B",
	"B       RBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB        B",
	"B                             B                             B",
	"B                                                           B",
	"B                                                           B",
	"BWWWWWWWW                BB       BB                WWWWWWWWB",
	"BWWWWWWWW                BB       BB                WWWWWWWWB",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBBBBWWWWWWB",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBB       BBBBBBBBBBBBBBBBBBBBWWWWWWB",
	"BFFFFFFFFFFFFFFFFFFFFFFFF           bb      bb     bb      UB",
	"BFFFFFFFFFFFFFFFFFFFFFFF            bb      bb     bb       B",
	"BFFFFFFFFFFFFFFFFFFFFFF             bb      bb     bb       B",
	"BFFFFFFFFFFFFFFFFFFFFF              bb      bb     bb       B",
	"BFFFFFFFFFFFFFFFFFWWWbbbbbbbbbBBBBBBBBBBBBBBBBBBBBBBBBWWWWWWB",
	"BFFFFFFFFFFFFFFFFFWWW                   bb      bb          B",
	"BFFFFFFFFFFFFFFFFFWWW                   bb      bb          B",
	"BFFFFFFFFFFFFFFFFFWWW                   bb      bb          B",
	"BWWWWWFFFFFFBWWWWWWW                    bb      bb       R  B",
	"BWWWWWFFFFFFBWW          BBBBBBBBBB    BBBBBBBBBBBBBBBBBBBBBB",
	"BWWWWWFFFFFFBWW         WWWWWWBWWWWbbbbbbbFFFFFFFFbbbbbbbbbbB",
	"BWWWWWFFFFFFBWW        WWWWWWWBWWWWRbbbbbbFFFFFFFFbbbbbbbbbbB",
	"BWWWWWFFFFFFBWW       WWWBBBBBBWWWWbbbbbbbFFFFFFFFbbbbbbbbbbB",
	"BbbbbbFFFFFFBWW      WWWWBBBBBBBBBBBBBBBBBBBBBBBBBbbbbbbbbbbB",
	"BAbbbbFFFFFFBWW     WWWWWBBBBBBWWWWbbbbbbb                  B",
	"BWWWWWFFFFFFBWW     WWWWWBBBBBBWWWWbbbbbbb                  B",
	"BWWWWWFFFFFFBWW     WWWWWBBBBBBWWWWRbbbbbb                  B",
	"BFFFFFFFFFFFBWW     WBBBBBBBBBBBBBBBBBBBBBBBBBBB            B",
	"BFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFWWWWWWFFFFFFFBBFFFFFFbbbbbbbbB",
	"BFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFWWWWWWFFFFFFFBBFFFFFFbbbbbbbbB",
	"BFFFFFWWWWBBBBBB         U     WWW          BB              B",
	"BFFFFFWWWW                     WWW          BB              B",
	"BFFFFFBBBB                     WWW          BB              B",
	"BFFFFFBBBB        R            BWB                  bbbbbbbbB",
	"BFFFFFBBBB                  bbBBBBBbb            R  bbbbbbbbB",
	"BFFFFFBBBB                  bBBBBBBBb                       B",
	"BFFFFFFFFFFFFFFFFFFFFFFFFFFFBWWWWWWWB                       B",
	"BFFFFFFFFFFFFFFFFFFFFFFFFFFFBW     WB                       B",
	"BFFFFFFFFFFFFFFFFFFFFFFFFFFFBW     WBFFFFFFFFFFFFFFFFFFFFFFFB",
	"BBBBWWWWWWWWWWWWBBBBBBFFFFFFBW     WBFFFFFFFFFFFFFFFFFFFFFFFB",
	"BBBBWWWWWWWWWWWWBBBBBBFFFFFFBB     BB                       B",
	"BBBBBBBBBBBBBBBBBBBBBBFFFFFFBB     BB                       B",
	"BBBBBBBBBBBBBBBBBBBBBBFFFFFFBB     BB      BBBBBBBBbbbbbbbbbB",
	"BBBBBBBBBBBBBBBBBBBBBBFFFFFFBB     BB      BBBBBBBBbbbbbbbbbB",
	"Bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb              bbbbbbbbbB",
	"Bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb              bbbbbbbbbB",
	"B                                                  bbbbbbbbbB",
	"B                                                  bbbbbbbbbB",
	"B                                                  bbbbbbbbbB",
	"BFFFF                 BBBB         BBBB            bbbbbbbbbB",
	"BFFFFFFFF    bbbb     BBBB         BBBB            bbbbbbbbbB",
	"BFFFFFFFFFFFFbbbb     bbbb         bbbb                 bbbbB",
	"BFFFFFFFFFFFFbbbbFFFFFFFFFFFFFFFFFFFFFFFFFFbbbb         bbbbB",
	"BFFFFFFFFFFFFbbbbFFFFFFFFFFFFFFFFFFFFFFFFFFbbbb         bbbbB",
	"BFFFFFFFFFFFFWWWWWW   BBBB         BBBB                 bbbbB",
	"BFFFFFFFF    WWWWWW   BBBB    R    BBBB                 WWWWB",
	"BFFFF                     BB     BB                     WWWWB",
	"B                         BBBBBBBBBbbbbbbbbbbbbbbbbbWWWWWWWWB",
	"B     bbbbFFFFbbbbbbb     bbbbbbbbb                 WWWWWWWWB",
	"B     bbbbFFFFbbbbbbb      bbbbbbb                  FFFFFWWWB",
	"B     bbbb      WWWW                                FFFFFFFFB",
	"B     bbbb      WWWW      R                                 B",
	"B     bbbb      WWWW                     bbbbbbbbbbb        B",
	"B     bbbb                               bbbbbbbbbbb        B",
	"B     bbbb                                                  B",
	"B                                                           B",
	"B   BBBBBBBBBB     WWWWWWWWWWWWWWWWWWWWWWW     BBBBBBBBBB   B",
	"BbbbWWWWFFFFFF     WWWWWWWWWWWWWWWWWWWWWWW     FFFFFFWWWWbbbB",
	"BbbbWWWWFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFWWWWbbbB",
	"BbbbWWWWbbbbFFFFFF                         FFFFFFbbbbWWWWbbbB",
	"BbbbWWWWbbbbFFFFFF   R               R     FFFFFFbbbbWWWWbbbB",
	"BbbbWWWWbbbWWWWWWWbb      bbbbbbb        bbWWWWWWWbbbWWWWbbbB",
	"BbbbWWWWbUbWWWWWWWbb      bbbbbbb        bbWWWWWWWbUbWWWWbbbB",
	"B                            B                              B",
	"B                            B                              B",
	"B            BBBBBBBBBBBB    B    BBBBBBBBBBBBB             B",
	"B                                                           B",
	"B                            C                              B",
	"B                                                           B",
	"BWWWWWWWWWWWWWWWWWWWWWWWWWWFFFFFFWWWWWWWWWWWWWWWWWWWWWWWWWWWB",
	"BWWWWWWWWWWWWWWWWWWWWWWWWWWFFFFFFWWWWWWWWWWWWWWWWWWWWWWWWWWWB",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBFFFFFFBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBWWWWWWWWWWWWWWWWFFFFFFWWWWWWWWWWWWWWWWWBBBBBBBBBBB",
	"BBBBBBBBBBWWWWWWWWWWWWWWWWWFFFFFFWWWWWWWWWWWWWWWWWWBBBBBBBBBB",
	"BBBBBBBBBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFBBBBBBBBB",
	"BBBBBBBBFFFFFFFFFbbbbbbbbbbbbbbbbbbbbbbbbbbbFFFFFFFFFBBBBBBBB",
	"BBBBBBBFFFFFFFFbbbbb                     bbbbbFFFFFFFFBBBBBBB",
	"BBBBBBFFFFFFFbbbbbbb                     bbbbbbbFFFFFFFBBBBBB",
	"BBBBBFFFFFFFbbbbbb                         bbbbbbFFFFFFFBBBBB",
	"BBBBFFFFFFFbbbbbbb                         bbbbbbbFFFFFFFBBBB",
	"BBBFFFFFFFbbbbbb                             bbbbbAFFFFFFFBBB",
	"BBFFFFFFFbbbbbbb                             bbbbbbbFFFFFFFBB",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
};
