#pragma once

const int seventhHeight = 119;
const int seventhWidth = 61;

string SeventhStage[] =
{
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                       bbbbbbbb                            B",
	"B                       bbbbbbbb                            B",
	"B                              b                            B",
	"B                             b                             B",
	"B                            b                              B",
	"B                           b                               B",
	"B                          b                                B",
	"B                         b                                 B",
	"B                        b                                  B",
	"B                       b                                   B",
	"B                       b                                   B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
};
