#pragma once

const int fifteenthHeight = 119;
const int fifteenthWidth = 61;

string FifteenthStage[] =
{
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                       b     bbbbbbb                       B",
	"B                      bb     b                             B",
	"B                     b b     b                             B",
	"B                    b  b     b bbbb                        B",
	"B                       b     bb    b                       B",
	"B                       b           b                       B",
	"B                       b           b                       B",
	"B                       b     b     b                       B",
	"B                       b     b     b                       B",
	"B                      bbb     bbbbb                        B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"B                                                           B",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
};
